spring.application.name=leadfinder

spring.datasource.url=jdbc:mysql://localhost:3306/leadfinder
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true